language: node_js
env:
  global:
    - "AWS_KEY=<YOUR_ECNRYPTED_AWS_KEY>"
    - "AWS_SECRET=<YOUR_ECNRYPTED_AWS_SECRET>"
node_js:
- '0.10'
before_script:
- npm install -g gulp
script:
- gulp build --release
after_success:
- gulp deploy
